### ISSUE TITLE
Baikal N+

### ISSUE THREAD

**Issue by alongnew** [altASIC/Open-CryptoNight-ASIC#1]
Can this code compile to Baikal Giant N+ ?

**Comment by powhacker** [comment]
Baikal or any other hardware manufacturer could incorporate this component into their system, whether it's FPGA or ASIC based.  It's not something you or I could do, like flashing a GPU.  This question is probably better asked of Baikal.  Note that this code only runs "Classic" CryptoNight and would need to be modified for many coins.

**Comment by timolson** [comment]
Baikal or any other hardware manufacturer could incorporate this component into their system, whether it's FPGA or ASIC based.  It's not something you or I could do, like flashing a GPU.  This question is probably better asked of Baikal.  Note that this code only runs "Classic" CryptoNight and would need to be modified for many coins.
