### ISSUE TITLE
AES

### ISSUE THREAD

**Issue by tevador** [altASIC/Open-CryptoNight-ASIC#2]
> Physical layout was completed vs TSMC 28nm process and parasitics extracted. Size of a single core was 4mm<sup>2</sup>. Clock rate was 800MHz, limited by RAM tpd. Power simulation measured 400 μJ per hash.

Can you provide a rough estimate how much of the 4mm<sup>2</sup> is for AES logic and how much of the 400 μJ can be attributed to AES ecryption?

**Comment by timolson** [comment]
Our license for that tool isn't active this month... The core area and power are dominated by scratchpad SRAM, roughly 93-95% SRAM and 5-7% for _all_ the logic to do the Initialization Loop, Main Loop, and Finalization Loop.  AES is reused across loops, of course.  Key expansion + the round function are maybe (just a guess, sorry) 3% of the core?  That would be around 0.1 mm2.  Power's a more complicated question that I can't evaluate right now, sorry.  Keep in mind we used 28nm...

**Comment by tevador** [comment]
Thanks. So it's about what I expected.
